### ISSUE TITLE
Change network discovery behavior

### ISSUE THREAD

**Issue by Solvik** [Solvik/netbox_agent#20]
We shouldn't hardcode the behavior of network interface discovery and instead use parameters in the configuration file to let the user choose what they want to ignore

That way we will manage corner cases of users having loopback IP (ipvs, bgp etc)
And also create vlan interfaces, which is not working right now

I propose something like:

```
network:
  ignore_interfaces: "(dummy.*|docker.*)"
  ignore_ips: "(127\.0\.0\..*)"
```

**Comment by ramnes** [comment]
A list of regular expressions to exclude would probably be simpler for users.
