### ISSUE TITLE
Hardware inventory update

### ISSUE THREAD

**Issue by ThomasADavis** [Solvik/netbox_agent#49]
![Screenshot from 2019-08-28 12-00-10](https://user-images.githubusercontent.com/12158973/63884664-76116780-c98b-11e9-8d1d-a7e36ee67bee.png)

So, memory, disk, network, CPU all nice and neat..  NVME is also partially included - I have another node that has this..

It doesn't use dmi to do this, it uses the output of lshw  to collect it.

I think I need to make the asset tags unique, so I was going to make it 'hostname:part'

thomas

**Comment by Solvik** [comment]
That's really better than the first version I've done, nice !
Personally I wouldn't use the asset tag in the case of server hardware

I've tried `lshw -json` when you previously mentionned it, and it's really better 

Do you have a PR for this ?

**Comment by ThomasADavis** [comment]
This is using the asset tag more as a locator than a tag..

I will have a PR shortly, still more cleanup is needed on my side.

**Comment by Solvik** [comment]
Awesome, looking forward to it :)

**Comment by Solvik** [comment]
I was thinking of something: we should add the motherboard in the inventory, what do you think ?

**Comment by ThomasADavis** [comment]
Agreed - motherboard is needed.

**Comment by Solvik** [comment]
Just merged #58 
Thanks a lot for your contribution !! it solves a lot of issues
